### ISSUE TITLE
What is the meaning of FLUSH_ON_STOP=0?

### ISSUE THREAD

**Issue by ivanleoncz** [zertrin/iptables-persistent#7]
Here I have the following file:

==========================================
$ cat /etc/default/netfilter-persistent 
#### Plugins may extend this file or have their own

FLUSH_ON_STOP=0

==========================================

My SO: Debian Jessie 8.9
Packet Version: netfilter-persistent /1.0.3+deb8u1

What is the meaning of this variable?

Thanks.

**Comment by zertrin** [comment]
I don't know. Please see the second paragraph of the readme of this repository. I am not related to netfilter-persistent.

Sorry
